### ISSUE TITLE
.get_parsers() doesn't work with nvim-treesitter's main branch.

### ISSUE THREAD

**Issue by dsully** [bezhermoso/tree-sitter-ghostty#9]
The change in f2eb6071cf3d85d1d872a0cc6c69d502e7fc3a60

```lua
local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
```

Via a plugin auto-load breaks when using `nvim-treesitter` on the `main` (not `master`) branch, as `.get_parser_configs()` doesn't exist anymore.

That entire block should be guarded with a `pcall` or made optional.

Thanks.

**Comment by bezhermoso** [comment]
Hi, thank you for the report! I was not aware that `nvim-treesitter` is undergoing a rewrite.

This should address this issue https://github.com/bezhermoso/tree-sitter-ghostty/pull/10

**Comment by dsully** [comment]
Thank you!
